[package]
name = "obs-celeste-transparent-webcam"
version = "0.1.0"
edition = "2024"

[dependencies]
ct-codecs = "1.1.7"
futures = { version = "0.3.34", default-features = false }
rmp-serde = "1.3.1"
serde = { version = "1.0.229", features = ["derive"] }
sha2 = "0.11.0"
tokio = { version = "1.53.1", features = ["full"] }
toml = "1.1.4"
tokio-tungstenite = "0.30.0"
