# any line starting with a # is a comment and will be ignored

[general]
# how long to check for CCT for position updates, in milliseconds
# might contribute to game lag if set too low
# one frame is 16 2/3 ms (16.6666666666666666666666666666666666...667ms)
position-polling-interval = 16

# obs websocket connection settings
[obs]
host = "127.0.0.1"
port = 4455
# uncomment this to use a password
# password = ""

[[source]]
# scene = "scene"
source = "webcam"
filter = "opacity"
enable-when-in-bounds = true
x-start = 0
y-start = 0
x-end = 0
y-end = 0

# to add more sources, add more sections starting with "[[source]]"
# and copy all of the options, then customise to your liking
# there is no limit on the amount of sources

# [[source]]
# # scene = "scene"
# source = "webcam"
# filter = "opacity"
# enable-when-in-bounds = true
# x-start = 0
# y-start = 0
# x-end = 0
# y-end = 0

# [[source]]
# # scene = "scene"
# source = "webcam"
# filter = "opacity"
# enable-when-in-bounds = true
# x-start = 0
# y-start = 0
# x-end = 0
# y-end = 0

# [[source]]
# # scene = "scene"
# source = "webcam"
# filter = "opacity"
# enable-when-in-bounds = true
# x-start = 0
# y-start = 0
# x-end = 0
# y-end = 0

# [[source]]
# # scene = "scene"
# source = "webcam"
# filter = "opacity"
# enable-when-in-bounds = true
# x-start = 0
# y-start = 0
# x-end = 0
# y-end = 0

# [[source]]
# # scene = "scene"
# source = "webcam"
# filter = "opacity"
# enable-when-in-bounds = true
# x-start = 0
# y-start = 0
# x-end = 0
# y-end = 0

# [[source]]
# # scene = "scene"
# source = "webcam"
# filter = "opacity"
# enable-when-in-bounds = true
# x-start = 0
# y-start = 0
# x-end = 0
# y-end = 0

# [[source]]
# # scene = "scene"
# source = "webcam"
# filter = "opacity"
# enable-when-in-bounds = true
# x-start = 0
# y-start = 0
# x-end = 0
# y-end = 0
